### PR TITLE
Do not access function fields after deleting its memory context

### LINKED ISSUE #1581: [Bug]: Intermittent crash in ResetTDSConnection
### What happened?

I am observing an intermittent backend crash that happens when [ResetTDSConnection](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tds/src/backend/tds/tdsprotocol.c#L113) is requested by client application.

`ResetTDSConnection` calls [reset_session_properties](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tds/src/backend/tds/tdsprotocol.c#L144) that eventually calls [reset_cached_batch](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L3223). And the crash happens in `pltsql_free_function_memory` on [this assignment](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_funcs.c#L868) when the `func` itself is already freed.

I am unable to get a stable reproduction or reproduce it without the client app, the crash happens for me only when the client app runs under load and ODBC connection pooling is enabled (so TDS reset is called on existing connection taken from the pool).

It seems that there can be a simple workaround for the problematic assignment, will submit a PR with it shortly.

### Version

BABEL_3_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Other

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by staticlibs**
### Description

When an anonymous code block is being executed, the compiled function for it [is allocated](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L1058) in the same memory context that is used for the contents of the function (`fn_cxt` field).

When `pltsql_free_function_memory` is called on such function, the memory context is being deleted first and [fn_cxt field is assigned after that](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_funcs.c#L868). That is effectively a "use after free" situation, but due to the memory contexts (and I assume libc allocator too) caching, this write almost never leads to a crash.

Proposed patch moves the assignment to `fn_cxt` to happen before the `MemoryContextDelete` call, otherwise the logic is kept the same.

I believe this fixes the root cause for #1581 (at least I cannot reproduce the problem with patch applied).

### Issues Resolved

#1581

### Test Scenarios Covered ###
* **Use case based -**

Unable to create a simple reproducer.

* **Boundary conditions -**

* **Arbitrary inputs -**

* **Negative test cases -**

* **Minor version upgrade tests -**

* **Major version upgrade tests -**

* **Performance tests -**

* **Tooling impact -**

* **Client tests -**

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: contrib/babelfishpg_tsql/src/pl_funcs.c [hunk 1]
```diff
@@ -864,8 +865,11 @@ pltsql_free_function_memory(PLtsql_function *func)
 	 * fn_extra pointers to it).
 	 */
 	if (func->fn_cxt)
-		MemoryContextDelete(func->fn_cxt);
```
Comment (kuntalghosh) [inline contrib/babelfishpg_tsql/src/pl_funcs.c:867]: The variable func->fn_cxt is a pointer. MemoryContextDelete frees up the memory pointed by func->fn_cxt and it doesn't free func->fn_cxt itself. You can't access func->fn_cxt if you do a pfree(func). But, that's not happening in this case.
```
func->fn_cxt = NULL
```
The above code just changes the pointer value to NULL. So, I don't see why it'll cause an usage of memory after free issue.

Comment (staticlibs) [reply contrib/babelfishpg_tsql/src/pl_funcs.c:867]: I well could have misread the existing logic in `pl_comp.c`, my reasoning was based on the following understanding:
 1. [func_cxt is set as a current memory context](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L1055)
 2. [function structure itself is allocated in current memory contex](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L1058)
 3. [the same memory context is assigned to fn_cxt field of the function](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L1066)

I assumed that, after "MemoryContextDelete will free up the memory pointed by func->fn_cxt" and when the function struct itself was allocated in this memory (using the same context) - then writes to the fields of this function structure will be "use after free" situation.

Comment (kuntalghosh) [reply contrib/babelfishpg_tsql/src/pl_funcs.c:867]: Actually, you are right. The function memory itself is being allocated in func->fn_cxt. And, we're accessing it from more than one place after it's freed. Apart from the one you've fixed, we also need to fix [this](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/aaa7127d18f01188b8945029eb5a27dc2298f378/contrib/babelfishpg_tsql/src/pl_comp.c#L224). Here, delete_function is freeing up the memory if usage count is 0, then again accessing the variable. Could you please include this in your fix as well?

Comment (staticlibs) [reply contrib/babelfishpg_tsql/src/pl_funcs.c:867]: Sorry for delay, will be able to update the PR in a few days.

Comment (staticlibs) [reply contrib/babelfishpg_tsql/src/pl_funcs.c:867]: Moved `use_count` check to happen before the `delete_function` call, the logic is kept the same.

**Comment by staticlibs** [comment]
Besides the `use_count` check, added some comments and rebased the branch to the latest.

**Review by kuntalghosh — APPROVED** [review]

**Review by 2jungkook — APPROVED** [review]
